# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapearth/api/v1/segmentation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snapearth/api/v1/segmentation.proto',
  package='snapearth.api.v1.segmentation',
  syntax='proto3',
  serialized_options=b'\n!com.snapearth.api.v1.segmentationB\021SegmentationProtoH\003P\001\242\002\004SAVS\252\002\035Snapearth.Api.V1.Segmentation\312\002\035Snapearth\\Api\\V1\\Segmentation\342\002)Snapearth\\Api\\V1\\Segmentation\\GPBMetadata\352\002 Snapearth::Api::V1::Segmentation',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#snapearth/api/v1/segmentation.proto\x12\x1dsnapearth.api.v1.segmentation\"N\n\x06Raster\x12\x16\n\x06height\x18\x02 \x01(\x05R\x06height\x12\x14\n\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n\x04\x64\x61ta\x18\x03 \x03(\rB\x02\x10\x01R\x04\x64\x61taB\xd0\x01\n!com.snapearth.api.v1.segmentationB\x11SegmentationProtoH\x03P\x01\xa2\x02\x04SAVS\xaa\x02\x1dSnapearth.Api.V1.Segmentation\xca\x02\x1dSnapearth\\Api\\V1\\Segmentation\xe2\x02)Snapearth\\Api\\V1\\Segmentation\\GPBMetadata\xea\x02 Snapearth::Api::V1::Segmentationb\x06proto3'
)




_RASTER = _descriptor.Descriptor(
  name='Raster',
  full_name='snapearth.api.v1.segmentation.Raster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='snapearth.api.v1.segmentation.Raster.height', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='height', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='snapearth.api.v1.segmentation.Raster.width', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='width', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='snapearth.api.v1.segmentation.Raster.data', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', json_name='data', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['Raster'] = _RASTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Raster = _reflection.GeneratedProtocolMessageType('Raster', (_message.Message,), {
  'DESCRIPTOR' : _RASTER,
  '__module__' : 'snapearth.api.v1.segmentation_pb2'
  # @@protoc_insertion_point(class_scope:snapearth.api.v1.segmentation.Raster)
  })
_sym_db.RegisterMessage(Raster)


DESCRIPTOR._options = None
_RASTER.fields_by_name['data']._options = None
# @@protoc_insertion_point(module_scope)
